"""
SHADOW MODE / GITHUB ISSUE DRY-RUN — RC15
Analyzes real GitHub issues in read-only shadow mode.
NEVER commits, pushes, or modifies original repos.

Full pipeline: Clone → Analyze → Diff → Sandbox → Test → Report.

Autor: Hermes + David | Coding Tentacle 2026
"""

# CT-v11.0.1: PRODUCTION | 24/24 tests | Exception audit passed | Droste v11.0.1-index
import os, time, json, tempfile, shutil, logging
from dataclasses import dataclass, field, asdict

logger = logging.getLogger(__name__)
from typing import Optional


@dataclass
class GitHubIssueRun:
    """Input: a GitHub issue to analyze."""
    repo_url: str              # "https://github.com/user/repo"
    issue_url: str             # "https://github.com/user/repo/issues/1"
    issue_title: str = ""
    issue_body: str = ""
    branch: str = "main"
    test_command: str = ""     # "pytest -x -q" or similar
    max_attempts: int = 2
    mode: str = "shadow"       # always shadow for now


@dataclass
class ShadowRunReport:
    """Output: complete analysis of one GitHub issue."""
    repo: str
    issue: str
    issue_title: str
    detected_bug_type: str = ""
    confidence: float = 0.0
    selected_procedure: str = ""
    selected_skill: str = ""
    generated_diff: str = ""
    engine_used: str = ""
    engine_fix_raw: str = ""
    skeptic_risk: float = 0.0
    skeptic_objections: list = field(default_factory=list)
    skeptic_recommendation: str = ""
    impact_risk: float = 0.0
    impacted_files: list = field(default_factory=list)
    impacted_tests: list = field(default_factory=list)
    approval_status: str = ""        # pending | approved | rejected | changes_requested
    approval_notes: str = ""
    blm_written: bool = False
    blm_error: str = ""
    droste_nodes: int = 0             # RC72: Droste context nodes count
    droste_budget_used: int = 0       # RC72: chars used by Droste context
    rules_updated: int = 0              # RC-W1: rules from ExperienceConsolidator
    consolidator_rule: str = ""           # RC-W1b: PREFER/AVOID rule applied
    bug_type_trust_source: str = ""       # RC-W2: global/blended/specific
    dampened_trust: float = 0.0            # RC-W3: trust after FeedbackDampener
    wm_session_id: str = ""                # RC-W4: WorkingMemory session
    reflection: dict = field(default_factory=dict)  # CT11.x: Reflection analysis
    transferable_lesson: str = ""          # CT11.x: Lesson for next bug
    lessons_applied: int = 0              # CT11.102: Past lessons used in prompt
    prompt_learning_used: bool = False    # CT11.x: PromptLearner template used
    security_blocked: bool = False        # RC11: SecurityBrain blocked
    security_risk_score: float = 0.0      # RC11: AST risk score
    trojan_source_clean: bool = True       # RC11: Trojan Source scan passed
    sandbox_result: dict = field(default_factory=dict)
    test_result: dict = field(default_factory=dict)
    safety_events: list = field(default_factory=list)
    failure_reasons: list = field(default_factory=list)
    recommendation: str = ""
    duration_ms: float = 0.0
    timestamp: float = 0.0
    
    def __post_init__(self):
        if self.timestamp == 0.0:
            self.timestamp = time.time()
    
    def to_markdown(self):
        safety = "✅ SAFE" if not self.safety_events else f"⚠️  {len(self.safety_events)} safety events"
        test_status = "✅ PASS" if self.test_result.get('success') else \
                      "❌ FAIL" if self.test_result else "⚪ NOT_RUN"
        return f"""# Shadow Run Report: {self.issue_title}

**Repo:** {self.repo}
**Issue:** {self.issue}
**Bug Type:** {self.detected_bug_type} (conf={self.confidence:.0%})

## Procedure & Skill
- Procedure: {self.selected_procedure or 'none'}
- Skill: {self.selected_skill or 'none'}

## Diff Generated
```diff
{self.generated_diff[:500] or '(no diff generated)'}
```

## Test Result
{test_status}

## Safety Events
{safety}

## Recommendation
{self.recommendation or 'Pending human review'}

---
*Generated by Coding Tentacle RC15 Shadow Mode*
"""


class ShadowModeRunner:
    """Analyzes GitHub issues in read-only shadow mode.
    NEVER commits, pushes, touches original repos."""
    
    def __init__(self, meta_brain=None, teacher=None, diff_generator=None,
                 sandbox_runner=None, test_runner=None, repair_loop=None,
                 approval_gate=None, project_map_class=None,
                 engine_router=None, safety_brain=None, skeptic_brain=None,
                 droste_client='auto'):
        self.meta_brain = meta_brain
        self.teacher = teacher
        self.diff_generator = diff_generator
        self.sandbox_runner = sandbox_runner
        self.test_runner = test_runner
        self.repair_loop = repair_loop
        self.approval_gate = approval_gate
        self.project_map_class = project_map_class
        self.engine_router = engine_router
        self.safety_brain = safety_brain or (meta_brain.safety if meta_brain else None)
        self.skeptic_brain = skeptic_brain
        
        # CT-v11.0.1: Auto-instantiate Droste client when available
        if droste_client == 'auto':
            try:
                from coding_tentacle.knowledge.droste_client import DrosteClient
                droste_root = os.path.expanduser('~/GEHIRN_BIBLIOTHEK')
                if os.path.exists(droste_root):
                    self.droste_client = DrosteClient(project_root=droste_root)
                else:
                    self.droste_client = DrosteClient(project_root=os.getcwd())
            except Exception as e:
                logger.warning('Droste auto-init failed: %s', e)
                self.droste_client = None
        else:
            self.droste_client = droste_client
        self._working_memory = None       # RC-W4: lazy-init
        self._bug_type_trust = None        # RC-W2: lazy-init
        self._feedback_dampener = None     # RC-W3: lazy-init
        self.runs = []
    
    def analyze_issue(self, run: GitHubIssueRun) -> ShadowRunReport:
        """Analyze a GitHub issue in full shadow mode pipeline."""
        t0 = time.time()
        
        report = ShadowRunReport(
            repo=run.repo_url,
            issue=run.issue_url,
            issue_title=run.issue_title,
        )
        
        # Extract repo name from URL
        repo_name = run.repo_url.rstrip('/').split('/')[-1]
        
        # ═══ STEP 1: Extract bug information from issue ═══
        bug_report = f"{run.issue_title}\n{run.issue_body}"[:500]
        
        # RC-W4: WorkingMemory — session context for this run
        try:
            from coding_tentacle.memory.working_memory import WorkingMemory
            if self._working_memory is None:
                self._working_memory = WorkingMemory()
            session_id = f"run_{int(time.time())}_{hash(run.issue_url) % 10000}"
            self._working_memory.create_session(session_id)
            self._working_memory.update_context(session_id, 'bug', bug_report[:200])
            report.wm_session_id = session_id
        except Exception as _e_noncrit:
            logger.debug('Non-critical: %s', _e_noncrit)
        
        # ═══ STEP 2: Create isolated workspace ═══
        workspace = tempfile.mkdtemp(prefix=f'ct_shadow_{repo_name}_')
        
        try:
            # Simple file setup for analysis
            code_context = {'file': f'{repo_name}/main.py', 'line': 1}
            
            # ═══ STEP 3: Classify bug type from issue text ═══
            bug_type = self._classify_bug_type(bug_report)
            report.detected_bug_type = bug_type
            report.confidence = 0.7 if bug_type != 'Unknown' else 0.2
            
            # ═══ STEP 3B: SecurityBrain — Trojan Source + AST Security Scan (RC11) ═══
            try:
                from coding_tentacle.security.trojan_source_scanner import TrojanSourceScanner
                from coding_tentacle.security.ast_security_analyzer import ASTSecurityAnalyzer
                
                # Trojan Source scan (issue title + body + any code context)
                trojan = TrojanSourceScanner()
                scan_text = bug_report + '\n' + code_context.get('code', '')
                trojan_result = trojan.scan(scan_text)
                report.trojan_source_clean = trojan_result.clean
                
                # AST Security scan (only if code_context has code)
                ast_result = None
                if code_context.get('code', '').strip():
                    ast_analyzer = ASTSecurityAnalyzer()
                    ast_result = ast_analyzer.analyze(code_context.get('code', ''))
                    report.security_risk_score = ast_result.risk_score
                
                # BLOCK if critical security issues found
                trojan_critical = any(f.risk == 'CRITICAL' for f in trojan_result.findings)
                ast_critical = ast_result and ast_result.num_critical > 0
                
                if trojan_critical or ast_critical:
                    report.security_blocked = True
                    report.safety_events.append(
                        f'SECURITY_BLOCK: Trojan={trojan_critical} AST_Critical={ast_critical}'
                    )
                    report.recommendation = 'BLOCKED by SecurityBrain — potential backdoor detected'
                    
                    # CT 11.x: Quick reflection for security blocks
                    try:
                        from coding_tentacle.learning.reflection_engine import ReflectionEngine
                        ref = ReflectionEngine().analyze(report)
                        report.reflection = ref.to_dict()
                        report.transferable_lesson = ref.transferable_lesson
                    except Exception as _e_noncrit:
                        logger.debug('Non-critical: %s', _e_noncrit)
                    
                    self.runs.append(report)
                    return report  # Skip engine call entirely
                    
            except Exception as _e_noncrit:
                logger.warning('Security scan degraded: %s', _e_noncrit)
            
            # ═══ STEP 4: MetaBrain analyzes ═══
            if self.meta_brain:
                decision = self.meta_brain.decide(bug_report, code_context=code_context)
                if decision['final_decision'] == 'BLOCK':
                    report.safety_events.append(decision.get('reason', 'Blocked'))
                    report.recommendation = "BLOCKED by Safety — cannot analyze"
                    report.duration_ms = (time.time() - t0) * 1000
                    return report
            
            # ═══ STEP 5: Select procedure/skill ═══
            if self.teacher and self.teacher.procedural_memory:
                proc = self.teacher.procedural_memory.find_procedure(bug_type)
                if proc:
                    report.selected_procedure = f"{bug_type}:python"
            if self.teacher and self.teacher.skill_store:
                skill = self.teacher.skill_store.best_skill_for(bug_type)
                if skill:
                    report.selected_skill = skill.name
            
            # ═══ STEP 6: Generate fix via Engine Router (RC40) ═══
            
            # CT 11.102: Reflection Retrieval — läuft IMMER (auch ohne Engine)
            try:
                import os as _os3
                blm_db3 = _os3.path.expanduser('~/.coding_tentacle/learning.db')
                if _os3.path.exists(blm_db3):
                    from coding_tentacle.memory.bug_learning_memory import BugLearningMemory as BLM2
                    blm_refl = BLM2(db_path=blm_db3)
                    refl_entries = blm_refl.find_similar(
                        f'REFLECTION:{bug_type}', bug_type=bug_type, limit=3)
                    lessons = []
                    for e in refl_entries:
                        summary = e.get('fix_summary', '') or ''
                        if summary and len(summary) > 10:
                            lessons.append(summary[:150])
                    if lessons:
                        blm_context += '\\nLEARNED LESSONS (from past reflections):\\n'
                        for l in lessons[:2]:
                            blm_context += f'  → {l}\\n'
                        report.lessons_applied = len(lessons)
            except Exception as e:
                logger.debug('Reflection retrieval: %s', e)
            
            # RC72: Droste causal code context for engine prompt
            droste_context = ''
            if self.droste_client:
                try:
                    ctx = self.droste_client.get_context(
                        query=f"{bug_type} {run.issue_title}"[:200],
                        budget=1200,
                    )
                    if ctx:
                        droste_context = ctx.to_prompt_context()
                        report.droste_nodes = ctx.selected_count
                        report.droste_budget_used = ctx.used
                except Exception as _e_noncrit:
                    logger.debug('Non-critical: %s', _e_noncrit)
            
            if self.engine_router and bug_type != 'SecurityRisk':
                try:
                    from coding_tentacle.orchestrator.engine_router import EngineRouter
                    from coding_tentacle.orchestrator.bug_type_trust import BugTypeSpecificTrust
                    
                    # RC-W2: BugTypeTrust for per-bug-type engine routing
                    if self._bug_type_trust is None:
                        self._bug_type_trust = BugTypeSpecificTrust(min_samples=3)
                    if not hasattr(self.engine_router, 'bug_type_trust') or self.engine_router.bug_type_trust is None:
                        self.engine_router.bug_type_trust = self._bug_type_trust
                    
                    # RC-W3: FeedbackDampener prevents over-confidence
                    if self._feedback_dampener is None:
                        from coding_tentacle.memory.feedback_dampener import FeedbackDampener
                        self._feedback_dampener = FeedbackDampener()
                    if not hasattr(self.engine_router, 'feedback_dampener') or self.engine_router.feedback_dampener is None:
                        self.engine_router.feedback_dampener = self._feedback_dampener
                    
                    # RC-W4-READ: Check WorkingMemory for past decisions
                    wm_context = ''
                    if self._working_memory is not None and report.wm_session_id:
                        try:
                            state = self._working_memory.get_state(report.wm_session_id)
                            if state and state.decisions:
                                engines_used = [d.get('action','') for d in state.decisions 
                                              if 'route_to_' in d.get('action','')]
                                if engines_used:
                                    wm_context = f'\nSESSION: Previously used: {", ".join(engines_used[-3:])}'
                        except Exception as e:
                            logger.debug('WM decision read: %s', e)
                    
                    # CT 11.102: Reflection Retrieval — past lessons for prompt
                    try:
                        import os as _os3
                        blm_db3 = _os3.path.expanduser('~/.coding_tentacle/learning.db')
                        if _os3.path.exists(blm_db3):
                            from coding_tentacle.memory.bug_learning_memory import BugLearningMemory as BLM2
                            blm_refl = BLM2(db_path=blm_db3)
                            refl_entries = blm_refl.find_similar(
                                f'REFLECTION:{bug_type}', bug_type=bug_type, limit=3)
                            lessons = []
                            for e in refl_entries:
                                summary = e.get('fix_summary', '') or ''
                                if summary and len(summary) > 10:
                                    lessons.append(summary[:150])
                            if lessons:
                                blm_context += '\\nLEARNED LESSONS (from past reflections):\\n'
                                for l in lessons[:2]:
                                    blm_context += f'  → {l}\\n'
                                report.lessons_applied = len(lessons)
                    except Exception as e:
                        logger.debug('BLM reflection retrieval: %s', e)
                    
                    engine_name, engine_cfg, route_reason = self.engine_router.route(bug_type)
                    report.engine_used = engine_name or 'none'
                    
                    # RC-W4: Record engine routing decision
                    try:
                        if self._working_memory is not None and report.wm_session_id:
                            self._working_memory.add_decision(report.wm_session_id,
                                f'route_to_{engine_name}', route_reason, 0.8)
                    except Exception as e:
                        logger.debug('Prompt learning: %s', e)
                    
                    # RC46 Fix2: BLM context enrichment for engine prompt
                    blm_context = ''
                    try:
                        import os as _os2
                        blm_db2 = _os2.path.expanduser('~/.coding_tentacle/learning.db')
                        if _os2.path.exists(blm_db2):
                            from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                            blm_read = BugLearningMemory(db_path=blm_db2)
                            similar = blm_read.find_similar(bug_report, bug_type=bug_type, limit=2)
                            if similar:
                                blm_context = '\\nSIMILAR PAST BUGS:\\n'
                                for s in similar[:2]:
                                    blm_context += f"- {s.get('bug_type','?')}: {str(s.get('bug_signature',''))[:80]} | fix: {s.get('fix_type','?')}\\n"
                            
                    except Exception as e:
                        logger.debug('BLM context enrichment: %s', e)
                    

                    
                    # CT 11.x Prompt Learning: Load best prompt template
                    prompt_template = None
                    try:
                        from coding_tentacle.learning.prompt_learner import PromptLearner
                        learner = PromptLearner()
                        best = learner.get_best_prompt(bug_type, engine_name)
                        if best:
                            prompt_template = best.prompt_template
                            report.prompt_learning_used = True
                    except Exception as e:
                        logger.debug('Prompt learning: %s', e)
                    
                    if engine_name and engine_cfg:
                        prompt = f"""Fix this bug. Output ONLY the corrected code or unified diff.

BUG: {run.issue_title}
DESCRIPTION: {run.issue_body[:300]}
{blm_context}
{droste_context}
BUG TYPE: {bug_type}

RULES: Output only the fix. Do NOT modify files. No commits. No PRs."""
                        
                        import subprocess
                        engine_path = engine_cfg.get('path', '')
                        if 'opencode' in engine_name.lower():
                            cmd = [engine_path, 'run', prompt]
                        elif 'claude' in engine_name.lower():
                            cmd = [engine_path, '-p', prompt]
                        elif 'ollama' in engine_name.lower():
                            cmd = ['ollama', 'run', 'granite3.2-vision', prompt]
                        else:
                            cmd = []
                        
                        if cmd:
                            try:
                                result = subprocess.run(cmd, capture_output=True, text=True, timeout=60, cwd='/tmp')
                                if result.returncode == 0:
                                    report.engine_fix_raw = (result.stdout + result.stderr)[:800]
                                    # Extract code block or diff from engine output
                                    output = report.engine_fix_raw
                                    if '```' in output:
                                        # Extract code between backticks
                                        parts = output.split('```')
                                        if len(parts) >= 2:
                                            report.generated_diff = parts[1].strip()
                                            if report.generated_diff.startswith('python'):
                                                report.generated_diff = report.generated_diff[6:].strip()
                                            elif report.generated_diff.startswith('diff'):
                                                report.generated_diff = report.generated_diff
                                    else:
                                        report.generated_diff = output[:500]
                            except subprocess.TimeoutExpired:
                                report.generated_diff = ''
                            except Exception as e:
                                logger.error('Engine execution failed: %s', e)
                                report.generated_diff = ''
                except ImportError:
                    pass  # Engine router not available, fall through to template
            
            # ═══ STEP 6B: SafetyBrain scan of engine-generated diff (RC42 Fix1) ═══
            if report.generated_diff and self.safety_brain:
                try:
                    from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                    blm = BugLearningMemory(db_path=os.path.join(workspace, 'safety_check.db'))
                    
                    # RC43B: decode Base64, HTML entities, string concatenation bypasses
                    import base64, html, re
                    decoded_text = report.generated_diff
                    try:
                        decoded_text += ' ' + base64.b64decode(report.generated_diff.encode()).decode('utf-8', errors='ignore')
                    except Exception:
                        pass  # base64 decode expected to fail on non-encoded text
                    decoded_text = html.unescape(decoded_text)
                    decoded_text += ' ' + re.sub(r"['\"]\\s*\\+\\s*['\"]", '', decoded_text)
                    
                    dangerous, patterns = blm.is_dangerous_pattern(decoded_text)
                    if dangerous:
                        report.safety_events.append(f'ENGINE_DIFF_DANGEROUS: {patterns}')
                        report.generated_diff = ''
                        report.recommendation = f'SAFETY BLOCK — engine diff contains: {patterns}'
                except Exception as e:
                    logger.error('SAFETY SCAN DEGRADED — continuing without diff safety check: %s', e)
                    report.safety_events.append('SAFETY_SCAN_DEGRADED')  # pipeline continues but is marked
            
            # ═══ STEP 6B.5: ImpactAnalyzer (RC48 Fix1) ═══
            if report.generated_diff:
                try:
                    from coding_tentacle.knowledge.impact_analyzer import ImpactAnalyzer
                    from coding_tentacle.knowledge.project_map import ProjectMap
                    pm = ProjectMap()
                    ia = ImpactAnalyzer(project_map=pm)
                    impact = ia.analyze(code_context.get('file', 'unknown'), 
                                       bug_type=bug_type, diff=report.generated_diff)
                    report.impact_risk = impact.risk_score
                    report.impacted_files = impact.impacted_files[:5]
                    report.impacted_tests = impact.impacted_tests[:3]
                    if impact.risk_score > 0.40:
                        report.skeptic_recommendation = 'REQUEST_MORE'
                except Exception as e:
                    logger.debug('Impact analysis: %s', e)  # bonus, not critical
            
            # ═══ STEP 6C: SkepticBrain review of engine diff (RC42 Fix3) ═══
            if report.generated_diff and hasattr(self, 'skeptic_brain') and self.skeptic_brain:
                try:
                    review = self.skeptic_brain.review(
                        bug_type=bug_type,
                        confidence=report.confidence,
                        teacher_trust=getattr(report, 'engine_trust', 0.70),
                        test_available=bool(report.test_result.get('success')) if report.test_result else False,
                        diff=report.generated_diff,  # RC48 Fix2: pass actual diff
                        impact_risk=getattr(report, 'impact_risk', 0.0),  # RC48 Fix1: impact context
                    )
                    report.skeptic_risk = review.risk_score
                    report.skeptic_objections = getattr(review, 'objections', [])
                    report.skeptic_recommendation = review.suggested_action
                    
                    if review.suggested_action == 'REJECT':
                        report.recommendation = f'SKEPTIC REJECT — risk={review.risk_score}'
                        report.approval_status = 'rejected'
                except Exception as e:
                    logger.warning('Skeptic review degraded: %s', e)  # important but non-fatal
            
            # Fallback: template-based diff (if no engine or engine failed)
            if not report.generated_diff and self.diff_generator and self.teacher:
                plan = self.teacher.create_plan(bug_report,
                    code_context=code_context,
                    grounding={'bug_type': bug_type, 'grounding_score': report.confidence})
                if plan:
                    patch_diff = self.diff_generator.generate(
                        plan, code_context=code_context,
                        original_code="# module\n\ndef main():\n    pass\n")
                    if patch_diff and patch_diff.diff:
                        report.generated_diff = patch_diff.diff[:500]
            
            # ═══ STEP 7: Sandbox test ═══
            if self.sandbox_runner and report.generated_diff:
                from coding_tentacle.patch.diff_generator import PatchDiff
                pd = PatchDiff(
                    file_path=code_context['file'], bug_type=bug_type,
                    original_code="# module", patched_code=report.generated_diff,
                    diff=report.generated_diff, confidence=report.confidence,
                    safety_checked=True, safety_passed=True,
                )
                sr = self.sandbox_runner.run(pd, project_path=workspace)
                report.sandbox_result = {
                    'success': sr.success,
                    'safety_status': sr.safety_status,
                    'patched_files': sr.patched_files,
                }
            
            # ═══ STEP 8: Test result ═══
            if self.test_runner and report.sandbox_result.get('success'):
                test_cmd = run.test_command or "python -m pytest -x -q"
                tr = self.test_runner.run(workspace, test_command=test_cmd)
                report.test_result = {
                    'success': tr.success,
                    'exit_code': tr.exit_code,
                    'tests_passed': tr.tests_passed,
                    'tests_failed': tr.tests_failed,
                }
            
            # ═══ STEP 8B: Human Approval Gate (RC41) ═══
            if self.approval_gate and report.generated_diff and not report.safety_events:
                report.approval_status = 'pending'
                report.approval_notes = 'Shadow mode — awaiting human decision'
                # In production: present to human, wait for approve/reject/request_changes
                # In shadow mode: mark as pending, continue with report
            
            # ═══ STEP 8C: BLM learning record (RC43B Fix) ═══
            try:
                from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                import os as _os
                blm_dir = _os.path.expanduser('~/.coding_tentacle')
                _os.makedirs(blm_dir, exist_ok=True)
                blm_db = _os.path.join(blm_dir, 'learning.db')
                blm = BugLearningMemory(db_path=blm_db)
                
                # RC-W1 FIX v3: Strict success — requires actual output
                blm_success = False
                if report.test_result and report.test_result.get('success'):
                    blm_success = True  # Tests passed = real success
                elif report.generated_diff and not report.safety_events:
                    blm_success = True  # Diff generated + safety clean = partial success
                # NOTE: classifier-only runs are NOT success — they produce no fix
                
                blm.record_experience(
                    bug_signature=f"{bug_type}: {run.issue_title[:80]}",
                    bug_type=bug_type,
                    fix_type=report.engine_used or 'template',
                    root_cause=f"Engine: {report.engine_used}" if report.engine_used else 'Unknown',
                    fix_summary=report.generated_diff[:100] if report.generated_diff else 'No diff',
                    file_path=code_context.get('file', 'unknown'),
                    language='python',
                    success=blm_success,
                )
                report.blm_written = True
                report.blm_error = ''
                
                # RC-W1: ExperienceConsolidator — only when enough new data
                try:
                    from coding_tentacle.memory.experience_consolidator import ExperienceConsolidator
                    # Only consolidate every 5 new experiences to avoid overwriting
                    if not hasattr(self, '_consolidation_counter'):
                        self._consolidation_counter = 0
                    self._consolidation_counter += 1
                    if self._consolidation_counter % 5 == 0:
                        consolidator = ExperienceConsolidator(min_samples=5)
                        consolidator.consolidate(blm)
                        report.rules_updated = len(consolidator.rules)
                    else:
                        report.rules_updated = -1  # Skipped — not enough new data
                    
                    # RC-W1b: Read consolidator rules back INTO pipeline
                    if report.engine_used and report.rules_updated > 0:
                        try:
                            rule_check = consolidator.check_fix(
                                bug_type, report.engine_used)
                            if rule_check:
                                action, conf = rule_check
                                report.consolidator_rule = f'{action}:{report.engine_used}:{conf:.0%}'
                                if action == 'PREFER':
                                    report.confidence = min(0.95, report.confidence + 0.05)
                                elif action == 'AVOID':
                                    report.confidence = max(0.10, report.confidence - 0.10)
                        except Exception as e:
                            logger.debug('Consolidator rule check: %s', e)
                except Exception as e:
                    logger.warning('Consolidation failed: %s', e)
                    report.rules_updated = -1
            except Exception as e:
                report.blm_written = False
                report.blm_error = str(e)[:200]
            
            # ═══ STEP 8D: EngineLearning record (RC46 Fix1+3) ═══
            if report.engine_used:
                try:
                    from coding_tentacle.orchestrator.engine_learning import EnginePerformanceStore
                    eps = EnginePerformanceStore()
                    # Fix 1: Correct success detection
                    success = False
                    if report.test_result:
                        success = bool(report.test_result.get('tests_passed', 0) > 0 or report.test_result.get('success'))
                    elif report.generated_diff and not report.safety_events:
                        success = True  # Diff generated + safety clean = partial success
                    elif report.skeptic_recommendation == 'APPROVE':
                        success = True
                    
                    eps.record(
                        engine_name=report.engine_used,
                        bug_type=bug_type,
                        success=success,
                        runtime_s=report.duration_ms / 1000 if report.duration_ms else 0,
                        skeptic_risk=getattr(report, 'skeptic_risk', 0.0),
                        impact_risk=getattr(report, 'impact_risk', 0.0),
                    )
                except Exception as _e_noncrit:
                    logger.debug('Engine learning: %s', _e_noncrit)
            
            # ═══ STEP 8D.5: Reflection Engine — Learn WHY (CT 11.x P0) ═══
            try:
                from coding_tentacle.learning.reflection_engine import ReflectionEngine
                reflector = ReflectionEngine()
                reflection = reflector.analyze(report)
                report.reflection = reflection.to_dict()
                report.transferable_lesson = reflection.transferable_lesson
                
                # Enrich BLM with reflection data
                if report.blm_written:
                    try:
                        blm_dir2 = os.path.expanduser('~/.coding_tentacle')
                        blm_db2 = os.path.join(blm_dir2, 'learning.db')
                        if os.path.exists(blm_db2):
                            from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                            blm2 = BugLearningMemory(db_path=blm_db2)
                            blm2.record_experience(
                                bug_signature=f"REFLECTION:{bug_type}:{run.issue_title[:50]}",
                                bug_type=bug_type,
                                fix_type=report.engine_used or 'template',
                                root_cause=getattr(report, 'root_cause', ''),
                                fix_summary=reflection.transferable_lesson[:200],
                                file_path=code_context.get('file', 'unknown'),
                                language='python',
                                success=True,  # REFLECTION is always valuable learning
                            )
                    except Exception as e:
                        logger.debug('Reflection BLM enrichment: %s', e)
            except Exception as e:
                logger.warning('Reflection engine degraded: %s', e)  # bonus, never blocks
            
            # CT 11.x: Save prompt + result for Prompt Learning
            if hasattr(report, 'engine_used') and report.engine_used:
                try:
                    from coding_tentacle.learning.prompt_learner import PromptLearner
                    learner = PromptLearner()
                    template = f"Fix {bug_type} in {{file}}. "
                    if report.droste_nodes > 0:
                        template += "Use Droste context. "
                    template += "Add guard clause or validation."
                    learner.record(
                        bug_type=bug_type,
                        engine=report.engine_used,
                        prompt_template=template,
                        success=report.reflection.get('success', False) if report.reflection else False,
                        droste_used=report.droste_nodes > 0,
                        droste_nodes=report.droste_nodes,
                        reflection_quality=0.7 if report.reflection.get('success') else 0.3,
                    )
                except Exception as e:
                    logger.debug('Prompt learner record: %s', e)
            
            # ═══ STEP 9: Recommendation ═══
            # RC-W4-READ: Session summary for report
            if self._working_memory is not None and report.wm_session_id:
                try:
                    summary = self._working_memory.summarize(report.wm_session_id)
                    if summary:
                        report.approval_notes = (report.approval_notes or '') + \
                            f' | WM: {summary.get("steps",0)} steps, {len(summary.get("brains_consulted",[]))} brains'
                except Exception as e:
                    logger.debug('WM summary: %s', e)
            
            if report.safety_events:
                report.recommendation = "DO NOT APPLY — Safety concern"
            elif report.test_result.get('success'):
                report.recommendation = "Ready for human review — tests pass in sandbox"
            elif report.detected_bug_type == 'Unknown':
                report.recommendation = "Cannot classify — needs human triage"
            else:
                report.recommendation = "Analyzed — needs human verification before apply"
            
        finally:
            # Cleanup workspace
            shutil.rmtree(workspace, ignore_errors=True)
        
        report.duration_ms = (time.time() - t0) * 1000
        self.runs.append(report)
        return report
    
    def _classify_bug_type(self, bug_report):
        """Classify bug type from issue text. 13+ types supported."""
        text = bug_report.lower()
        
        # Core types (6 — existing, high confidence)
        if any(w in text for w in ['null', 'none', 'nonetype', 'none reference',
                                     'has no attribute', 'optional', 'none value']):
            return 'NullPointer'
        if any(w in text for w in ['type', 'typeerror', 'cannot concatenate',
                                     'unsupported operand', 'multiply.*non-int', 'str and int',
                                     'bytes', 'str and bytes']):
            return 'TypeError'
        if any(w in text for w in ['import', 'modulenotfound', 'no module',
                                     'cannot import', 'circular import']):
            return 'ImportError'
        if any(w in text for w in ['attribute', 'attributeerror', 'has no attribute']):
            if not any(w in text for w in ['none', 'nonetype']):
                return 'AttributeError'
        if any(w in text for w in ['key', 'keyerror', 'missing key']):
            return 'KeyError'
        
        # Extended types (7 NEW — RC15.7)
        if any(w in text for w in ['indexerror', 'list index', 'out of range',
                                     'off-by-one', 'index out of bounds']):
            return 'IndexError'
        if any(w in text for w in ['valueerror', 'invalid literal', 'invalid value',
                                     'string where int', 'invalid for int']):
            return 'ValueError'
        if any(w in text for w in ['memoryerror', 'out of memory', 'oom',
                                     'memory leak', 'garbage collection']):
            return 'MemoryError'
        if any(w in text for w in ['syntaxerror', 'invalid syntax', 'syntax error',
                                     'version mismatch', 'python version']):
            return 'SyntaxError'
        if any(w in text for w in ['connection', 'connectionrefused', 'timeout',
                                     'refused', 'network', 'connection error']):
            return 'ConnectionError'
        if any(w in text for w in ['race condition', 'racecondition', 'deadlock',
                                     'concurrency', 'thread safety', 'startup race']):
            return 'RaceCondition'
        if any(w in text for w in ['performance', 'slow', 'n+1', 'loading',
                                     'load time', 'page load', 'optimiz']):
            return 'Performance'
        
        # Security (highest priority — check LAST to avoid false positives)
        if any(w in text for w in ['drop table', 'sql injection', 'xss',
                                     'eval(', 'shell injection', 'api_key']):
            return 'SecurityRisk'
        
        return 'Unknown'
    
    def run_batch(self, issues: list[GitHubIssueRun]) -> list[ShadowRunReport]:
        """Analyze multiple issues sequentially."""
        results = []
        for issue in issues:
            result = self.analyze_issue(issue)
            results.append(result)
        return results
    
    def stats(self):
        return {
            'total_runs': len(self.runs),
            'classified': sum(1 for r in self.runs if r.detected_bug_type != 'Unknown'),
            'safety_blocked': sum(1 for r in self.runs if r.safety_events),
            'actions_executed': 0,
        }


# ═══════════ TEST ═══════════
if __name__ == "__main__":
    from coding_tentacle.orchestrator.metabrain import MetaBrain, SafetyBrain
    from coding_tentacle.safety.inhibitory_control import InhibitoryControl
    from coding_tentacle.knowledge.security_store import create_seed_security_store
    from coding_tentacle.orchestrator.teacher_student import Teacher
    from coding_tentacle.patch.diff_generator import DiffGenerator
    from coding_tentacle.patch.patch_suggestion import PatchSuggestionEngine
    from coding_tentacle.knowledge.droste_client import DrosteClient
    
    print("SHADOW MODE / GITHUB ISSUE DRY-RUN — Self-Test")
    print("=" * 55)
    passed = 0
    
    sec = create_seed_security_store()
    ic = InhibitoryControl(security_store=sec)
    safety = SafetyBrain(ic=ic, security_store=sec)
    mb = MetaBrain(safety=safety)
    t = Teacher()
    ps = PatchSuggestionEngine()
    dg = DiffGenerator(safety_brain=safety, patch_suggestion=ps)
    droste = DrosteClient(
        project_root=os.path.expanduser(
            os.path.expanduser('~/coding-tentacle')
        )
    )
    runner = ShadowModeRunner(meta_brain=mb, teacher=t, diff_generator=dg,
                              droste_client=droste)
    
    # T1: Analyze safe issue
    issue1 = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/1",
        issue_title="NullPointerException when accessing user profile",
        issue_body="Getting NoneType error when user profile is not loaded.",
    )
    report = runner.analyze_issue(issue1)
    t1 = report.detected_bug_type != 'Unknown'
    print(f"  T1: {'✅' if t1 else '❌'} Safe issue → {report.detected_bug_type}")
    
    # T2: Report has recommendation
    t2 = bool(report.recommendation)
    print(f"  T2: {'✅' if t2 else '❌'} Recommendation → {report.recommendation[:60]}")
    
    # T3: Diff generated
    t3 = bool(report.generated_diff)
    print(f"  T3: {'✅' if t3 else '❌'} Diff generated → {len(report.generated_diff)} chars")
    
    # T4: Security issue blocked
    issue_sec = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/2",
        issue_title="SQL Injection in login form",
        issue_body="DROP TABLE users via eval() injection",
    )
    report_sec = runner.analyze_issue(issue_sec)
    t4 = report_sec.detected_bug_type == 'SecurityRisk' or len(report_sec.safety_events) > 0
    print(f"  T4: {'✅' if t4 else '❌'} Security issue → {report_sec.detected_bug_type}")
    
    # T5: Unknown issue handled
    issue_unk = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/3",
        issue_title="Something is broken",
        issue_body="I don't know what happened but the app crashed.",
    )
    report_unk = runner.analyze_issue(issue_unk)
    t5 = report_unk.detected_bug_type == 'Unknown'
    print(f"  T5: {'✅' if t5 else '❌'} Unknown issue → {report_unk.detected_bug_type}")
    
    # T6: Markdown report
    md = report.to_markdown()
    t6 = 'Shadow Run Report' in md and 'Bug Type' in md
    print(f"  T6: {'✅' if t6 else '❌'} Markdown report → {len(md)} chars")
    
    # T7: Stats read-only
    st = runner.stats()
    t7 = st['actions_executed'] == 0
    print(f"  T7: {'✅' if t7 else '❌'} Stats → read-only")
    
    passed = sum([t1,t2,t3,t4,t5,t6,t7])
    print(f"\n  {'='*55}")
    print(f"  ERGEBNIS: {passed}/7 Tests bestanden")
    print(f"  {'✅ SHADOW MODE FERTIG' if passed >= 6 else '⚠️'}")
