"""
SHADOW MODE / GITHUB ISSUE DRY-RUN — RC15
Analyzes real GitHub issues in read-only shadow mode.
NEVER commits, pushes, or modifies original repos.

Full pipeline: Clone → Analyze → Diff → Sandbox → Test → Report.

Autor: Hermes + David | Coding Tentacle 2026
"""
import os, time, json, tempfile, shutil
from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass
class GitHubIssueRun:
    """Input: a GitHub issue to analyze."""
    repo_url: str              # "https://github.com/user/repo"
    issue_url: str             # "https://github.com/user/repo/issues/1"
    issue_title: str = ""
    issue_body: str = ""
    branch: str = "main"
    test_command: str = ""     # "pytest -x -q" or similar
    max_attempts: int = 2
    mode: str = "shadow"       # always shadow for now


@dataclass
class ShadowRunReport:
    """Output: complete analysis of one GitHub issue."""
    repo: str
    issue: str
    issue_title: str
    injection_detected: bool = False
    injection_severity: str = 'none'
    injection_attack_type: str = ''
    observation: str = ""
    evidence_ledger_path: str = ""
    detected_bug_type: str = 'Unknown'
    confidence: float = 0.0
    selected_procedure: str = ""
    selected_skill: str = ""
    generated_diff: str = ""
    engine_used: str = ""
    engine_fix_raw: str = ""
    skeptic_risk: float = 0.0
    skeptic_objections: list = field(default_factory=list)
    skeptic_recommendation: str = ""
    impact_risk: float = 0.0
    impacted_files: list = field(default_factory=list)
    impacted_tests: list = field(default_factory=list)
    root_cause: str = ""
    root_cause_confidence: float = 0.0
    root_cause_evidence: list = field(default_factory=list)
    causal_chain: str = ""
    approval_status: str = ""        # pending | approved | rejected | changes_requested
    approval_notes: str = ""
    blm_written: bool = False
    blm_error: str = ""
    sandbox_result: dict = field(default_factory=dict)
    test_result: dict = field(default_factory=dict)
    safety_events: list = field(default_factory=list)
    failure_reasons: list = field(default_factory=list)
    recommendation: str = ""
    duration_ms: float = 0.0
    timestamp: float = 0.0
    
    def __post_init__(self):
        if self.timestamp == 0.0:
            self.timestamp = time.time()
    
    def to_markdown(self):
        safety = "✅ SAFE" if not self.safety_events else f"⚠️  {len(self.safety_events)} safety events"
        test_status = "✅ PASS" if self.test_result.get('success') else \
                      "❌ FAIL" if self.test_result else "⚪ NOT_RUN"
        return f"""# Shadow Run Report: {self.issue_title}

**Repo:** {self.repo}
**Issue:** {self.issue}
**Bug Type:** {self.detected_bug_type} (conf={self.confidence:.0%})

## Procedure & Skill
- Procedure: {self.selected_procedure or 'none'}
- Skill: {self.selected_skill or 'none'}

## Diff Generated
```diff
{self.generated_diff[:500] or '(no diff generated)'}
```

## Test Result
{test_status}

## Safety Events
{safety}

## Recommendation
{self.recommendation or 'Pending human review'}

---
*Generated by Coding Tentacle RC15 Shadow Mode*
"""


class ShadowModeRunner:
    """Analyzes GitHub issues in read-only shadow mode.
    NEVER commits, pushes, touches original repos."""
    
    def __init__(self, meta_brain=None, teacher=None, diff_generator=None,
                 sandbox_runner=None, test_runner=None, repair_loop=None,
                 approval_gate=None, project_map_class=None,
                 engine_router=None, safety_brain=None, skeptic_brain=None):
        self.meta_brain = meta_brain
        self.teacher = teacher
        self.diff_generator = diff_generator
        self.sandbox_runner = sandbox_runner
        self.test_runner = test_runner
        self.repair_loop = repair_loop
        self.approval_gate = approval_gate
        self.project_map_class = project_map_class
        self.engine_router = engine_router
        self.safety_brain = safety_brain or (meta_brain.safety if meta_brain else None)
        self.skeptic_brain = skeptic_brain
        self.runs = []
    
    def analyze_issue(self, run: GitHubIssueRun) -> ShadowRunReport:
        """Analyze a GitHub issue in full shadow mode pipeline."""
        t0 = time.time()
        
        report = ShadowRunReport(
            repo=run.repo_url,
            issue=run.issue_url,
            issue_title=run.issue_title,
        )
        
        # ═══ STEP 0: REFLEX LAYER (RC52) — runs BEFORE everything ═══
        try:
            from coding_tentacle.brains.reflex_layer import ReflexLayer, VarietyMonitor
            reflex = ReflexLayer()
            vm = VarietyMonitor()
            reflex_report = reflex.scan(bug_report)
            if reflex_report.reflex_blocked:
                report.recommendation = f'REFLEX BLOCK: {reflex_report.reflex_reason}'
                report.run_time = time.time() - t0
                self.history.append(report)
                return report  # Block immediately — no engine, no analysis
            if reflex_report.recommendation == 'REQUEST_MORE':
                report.recommendation = f'REFLEX: {reflex_report.reflex_reason}'
        except Exception:
            pass  # Reflex layer is bonus
        
        # ═══ STEP 0B: VARIETY CHECK (RC52) ═══
        try:
            vm = VarietyMonitor()
            variety_report = vm.check(
                bug_type='Unknown',
                blm_similar_count=0
            )
            if variety_report.recommendation == 'REQUEST_MORE':
                if not report.recommendation:
                    report.recommendation = f'VARIETY: {variety_report.variety_details}'
        except Exception:
            pass
        
        # ═══ STEP 0C: HOMEOSTASIS CHECK (RC53) ═══
        try:
            from coding_tentacle.brains.homeostasis_brain import HomeostasisBrain
            hb = HomeostasisBrain()
            homeo_report = hb.check(
                engine_trust=getattr(self, '_last_trust', 0.60),
                error_rate=getattr(self, '_error_rate', 0.0),
                blm_entries=getattr(self, '_blm_count', 10),
                response_time=0.0,
                safety_active=self.safety_brain is not None,
                approval_active=self.approval_gate is not None,
                reflex_active=True,
                injection_active=True,
            )
            if homeo_report.status == 'CRITICAL':
                report.recommendation = f'HOMEOSTASIS CRITICAL: {homeo_report.detected_imbalances}'
                report.run_time = time.time() - t0
                self.history.append(report)
                return report
        except Exception:
            pass
        
        # ═══ STEP 0C.1: VITAL INTERACTION MATRIX (RC62) ═══
        try:
            from coding_tentacle.brains.vital_interaction_matrix import VitalInteractionMatrix
            vim = VitalInteractionMatrix()
            interaction_report = vim.analyze({
                'engine_trust': getattr(self, '_last_trust', 0.60),
                'error_rate': getattr(self, '_error_rate', 0.0),
                'blm_entries': getattr(self, '_blm_count', 10),
                'response_time': 0.0,
                'unknown_rate': 0.0,
                'audit_score': 1.0,
                'safety_active': self.safety_brain is not None,
                'engine_usage_ratio': 0.50,
                'calibration_gap': 0.0,
                'last_consolidation_age': 0,
            })
            if interaction_report.interaction_score < 0.30:
                report.recommendation = f'INTERACTION CRITICAL: {interaction_report.explanation}'
                report.run_time = time.time() - t0
                self.history.append(report)
                return report
        except Exception:
            pass
        
        # ═══ STEP 0D: SELF-HEALING CHECK (RC56) ═══
        try:
            from coding_tentacle.brains.self_healing_brain import SelfHealingBrain
            shb = SelfHealingBrain()
            heal_report = shb.monitor_and_heal(
                engine_trust=getattr(self, '_last_trust', 0.60),
                engine_name='opencode',
            )
            if heal_report.status == 'CRITICAL':
                report.recommendation = f'SELF-HEALING CRITICAL: {heal_report.detected_problem}'
                report.run_time = time.time() - t0
                self.history.append(report)
                return report
        except Exception:
            pass
        
        # ═══ STEP 0E: DEUTERO-LEARNING CHECK (RC57) ═══
        try:
            from coding_tentacle.brains.deutero_learning_brain import DeuteroLearningBrain
            dlb = DeuteroLearningBrain()
            dl_report = dlb.evaluate(
                engine_trusts={'opencode': 0.75, 'ollama': 0.40, 'claude': 0.65},
                engine_usage={'opencode': 5, 'ollama': 2, 'claude': 1},
            )
            if dl_report.status == 'CRITICAL':
                if not report.recommendation:
                    report.recommendation = f'LEARNING CRITICAL: {dl_report.detected_pathologies}'
        except Exception:
            pass
        
        # ═══ STEP 0A: Prompt Injection Detection (RC51) ═══
        try:
            from coding_tentacle.brains.prompt_injection_brain import PromptInjectionBrain
            pi_brain = PromptInjectionBrain()
            injection_report = pi_brain.analyze(bug_report)
            report.injection_detected = injection_report.injection_detected
            report.injection_severity = injection_report.severity
            report.injection_attack_type = injection_report.attack_type
            
            if injection_report.recommendation == 'BLOCK':
                report.recommendation = f'SAFETY BLOCK — prompt injection: {injection_report.attack_type}'
                report.run_time = time.time() - t0
                self.history.append(report)
                return report  # Don't send injection to LLM
        except Exception:
            pass  # Injection detection is bonus, not critical
        
        # Extract repo name from URL
        repo_name = run.repo_url.rstrip('/').split('/')[-1]
        
        # ═══ STEP 1: Extract bug information from issue ═══
        bug_report = f"{run.issue_title}\n{run.issue_body}"[:500]
        
        # ═══ STEP 2: Create isolated workspace ═══
        workspace = tempfile.mkdtemp(prefix=f'ct_shadow_{repo_name}_')
        
        try:
            # Simple file setup for analysis
            code_context = {'file': f'{repo_name}/main.py', 'line': 1}
            
            # ═══ STEP 3: Classify bug type from issue text ═══
            bug_type = self._classify_bug_type(bug_report)
            report.detected_bug_type = bug_type
            report.confidence = 0.7 if bug_type != 'Unknown' else 0.2
            
            # ═══ STEP 3B: Root Cause Analysis (RC50) ═══
            try:
                from coding_tentacle.brains.root_cause_brain import RootCauseBrain
                import os as _os3
                blm_db3 = _os3.path.expanduser('~/.coding_tentacle/learning.db')
                similar = []
                if _os3.path.exists(blm_db3):
                    from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                    blm_tmp = BugLearningMemory(db_path=blm_db3)
                    similar = blm_tmp.find_similar(bug_report, bug_type=bug_type, limit=3)
                
                rc_brain = RootCauseBrain()
                rc_report = rc_brain.analyze(bug_type, bug_report=bug_report,
                    impacted_files=[code_context.get('file', 'unknown')],
                    blm_similar=similar)
                
                report.root_cause = rc_report.root_cause
                report.root_cause_confidence = rc_report.confidence
                report.root_cause_evidence = rc_report.evidence
            except Exception:
                pass
            
            # ═══ STEP 3C: Causal Chain Graph (RC58) ═══
            try:
                from coding_tentacle.brains.causal_chain_graph import CausalChainGraph
                ccg = CausalChainGraph()
                chain = ccg.trace(
                    bug_type=bug_type, bug_report=bug_report,
                    affected_file=code_context.get('file', 'unknown'),
                    impacted_files=code_context.get('impacted_files', []),
                    root_cause=report.root_cause,
                )
                report.causal_chain = chain.ascii_diagram
            except Exception:
                pass  # Root cause analysis is bonus
            
            # ═══ STEP 4: MetaBrain analyzes ═══
            if self.meta_brain:
                decision = self.meta_brain.decide(bug_report, code_context=code_context)
                if decision['final_decision'] == 'BLOCK':
                    report.safety_events.append(decision.get('reason', 'Blocked'))
                    report.recommendation = "BLOCKED by Safety — cannot analyze"
                    report.duration_ms = (time.time() - t0) * 1000
                    return report
            
            # ═══ STEP 5: Select procedure/skill ═══
            if self.teacher and self.teacher.procedural_memory:
                proc = self.teacher.procedural_memory.find_procedure(bug_type)
                if proc:
                    report.selected_procedure = f"{bug_type}:python"
            if self.teacher and self.teacher.skill_store:
                skill = self.teacher.skill_store.best_skill_for(bug_type)
                if skill:
                    report.selected_skill = skill.name
            
            # ═══ STEP 6: Generate fix via Engine Router (RC40) ═══
            if self.engine_router and bug_type != 'SecurityRisk':
                try:
                    from coding_tentacle.orchestrator.engine_router import EngineRouter
                    engine_name, engine_cfg, route_reason = self.engine_router.route(bug_type)
                    report.engine_used = engine_name or 'none'
                    
                    # RC46 Fix2: BLM context enrichment for engine prompt
                    blm_context = ''
                    try:
                        import os as _os2
                        blm_db2 = _os2.path.expanduser('~/.coding_tentacle/learning.db')
                        if _os2.path.exists(blm_db2):
                            from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                            blm_read = BugLearningMemory(db_path=blm_db2)
                            similar = blm_read.find_similar(bug_report, bug_type=bug_type, limit=2)
                            if similar:
                                blm_context = '\\nSIMILAR PAST BUGS:\\n'
                                for s in similar[:2]:
                                    blm_context += f"- {s.get('bug_type','?')}: {str(s.get('bug_signature',''))[:80]} | fix: {s.get('fix_type','?')}\\n"
                    except Exception:
                        pass
                    
                    if engine_name and engine_cfg:
                        prompt = f"""Fix this bug. Output ONLY the corrected code or unified diff.

BUG: {run.issue_title}
DESCRIPTION: {run.issue_body[:300]}
{blm_context}
BUG TYPE: {bug_type}
ROOT CAUSE: {report.root_cause} (confidence: {report.root_cause_confidence:.0%})

RULES: Output only the fix. Do NOT modify files. No commits. No PRs."""
                        
                        import subprocess
                        engine_path = engine_cfg.get('path', '')
                        if 'opencode' in engine_name.lower():
                            cmd = [engine_path, 'run', prompt]
                        elif 'claude' in engine_name.lower():
                            cmd = [engine_path, '-p', prompt]
                        elif 'ollama' in engine_name.lower():
                            cmd = ['ollama', 'run', 'granite3.2-vision', prompt]
                        else:
                            cmd = []
                        
                        if cmd:
                            try:
                                result = subprocess.run(cmd, capture_output=True, text=True, timeout=60, cwd='/tmp')
                                if result.returncode == 0:
                                    report.engine_fix_raw = (result.stdout + result.stderr)[:800]
                                    # Extract code block or diff from engine output
                                    output = report.engine_fix_raw
                                    if '```' in output:
                                        # Extract code between backticks
                                        parts = output.split('```')
                                        if len(parts) >= 2:
                                            report.generated_diff = parts[1].strip()
                                            if report.generated_diff.startswith('python'):
                                                report.generated_diff = report.generated_diff[6:].strip()
                                            elif report.generated_diff.startswith('diff'):
                                                report.generated_diff = report.generated_diff
                                    else:
                                        report.generated_diff = output[:500]
                            except subprocess.TimeoutExpired:
                                report.generated_diff = ''
                            except Exception:
                                report.generated_diff = ''
                except ImportError:
                    pass  # Engine router not available, fall through to template
            
            # ═══ STEP 6B: SafetyBrain scan of engine-generated diff (RC42 Fix1) ═══
            if report.generated_diff and self.safety_brain:
                try:
                    from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                    blm = BugLearningMemory(db_path=os.path.join(workspace, 'safety_check.db'))
                    
                    # RC43B: decode Base64, HTML entities, string concatenation bypasses
                    import base64, html, re
                    decoded_text = report.generated_diff
                    try:
                        decoded_text += ' ' + base64.b64decode(report.generated_diff.encode()).decode('utf-8', errors='ignore')
                    except: pass
                    decoded_text = html.unescape(decoded_text)
                    decoded_text += ' ' + re.sub(r"['\"]\\s*\\+\\s*['\"]", '', decoded_text)
                    
                    dangerous, patterns = blm.is_dangerous_pattern(decoded_text)
                    if dangerous:
                        report.safety_events.append(f'ENGINE_DIFF_DANGEROUS: {patterns}')
                        report.generated_diff = ''
                        report.recommendation = f'SAFETY BLOCK — engine diff contains: {patterns}'
                except Exception:
                    pass  # Safety check failed, continue with caution
            
            # ═══ STEP 6B.5: ImpactAnalyzer (RC48 Fix1) ═══
            if report.generated_diff:
                try:
                    from coding_tentacle.knowledge.impact_analyzer import ImpactAnalyzer
                    from coding_tentacle.knowledge.project_map import ProjectMap
                    pm = ProjectMap()
                    ia = ImpactAnalyzer(project_map=pm)
                    impact = ia.analyze(code_context.get('file', 'unknown'), 
                                       bug_type=bug_type, diff=report.generated_diff)
                    report.impact_risk = impact.risk_score
                    report.impacted_files = impact.impacted_files[:5]
                    report.impacted_tests = impact.impacted_tests[:3]
                    if impact.risk_score > 0.40:
                        report.skeptic_recommendation = 'REQUEST_MORE'
                except Exception:
                    pass  # Impact analysis is bonus, not critical
            
            # ═══ STEP 6C: SkepticBrain review of engine diff (RC42 Fix3) ═══
            if report.generated_diff and hasattr(self, 'skeptic_brain') and self.skeptic_brain:
                try:
                    review = self.skeptic_brain.review(
                        bug_type=bug_type,
                        confidence=report.confidence,
                        teacher_trust=getattr(report, 'engine_trust', 0.70),
                        test_available=bool(report.test_result.get('success')) if report.test_result else False,
                        diff=report.generated_diff,  # RC48 Fix2: pass actual diff
                        impact_risk=getattr(report, 'impact_risk', 0.0),  # RC48 Fix1: impact context
                    )
                    report.skeptic_risk = review.risk_score
                    report.skeptic_objections = getattr(review, 'objections', [])
                    report.skeptic_recommendation = review.suggested_action
                    
                    if review.suggested_action == 'REJECT':
                        report.recommendation = f'SKEPTIC REJECT — risk={review.risk_score}'
                        report.approval_status = 'rejected'
                except Exception:
                    pass  # Skeptic review failed, continue
            
            # Fallback: template-based diff (if no engine or engine failed)
            if not report.generated_diff and self.diff_generator and self.teacher:
                plan = self.teacher.create_plan(bug_report,
                    code_context=code_context,
                    grounding={'bug_type': bug_type, 'grounding_score': report.confidence})
                if plan:
                    patch_diff = self.diff_generator.generate(
                        plan, code_context=code_context,
                        original_code="# module\n\ndef main():\n    pass\n")
                    if patch_diff and patch_diff.diff:
                        report.generated_diff = patch_diff.diff[:500]
            
            # ═══ STEP 7: Sandbox test ═══
            if self.sandbox_runner and report.generated_diff:
                from coding_tentacle.patch.diff_generator import PatchDiff
                pd = PatchDiff(
                    file_path=code_context['file'], bug_type=bug_type,
                    original_code="# module", patched_code=report.generated_diff,
                    diff=report.generated_diff, confidence=report.confidence,
                    safety_checked=True, safety_passed=True,
                )
                sr = self.sandbox_runner.run(pd, project_path=workspace)
                report.sandbox_result = {
                    'success': sr.success,
                    'safety_status': sr.safety_status,
                    'patched_files': sr.patched_files,
                }
            
            # ═══ STEP 8: Test result ═══
            if self.test_runner and report.sandbox_result.get('success'):
                test_cmd = run.test_command or "python -m pytest -x -q"
                tr = self.test_runner.run(workspace, test_command=test_cmd)
                report.test_result = {
                    'success': tr.success,
                    'exit_code': tr.exit_code,
                    'tests_passed': tr.tests_passed,
                    'tests_failed': tr.tests_failed,
                }
            
            # ═══ STEP 8B: Human Approval Gate (RC41) ═══
            if self.approval_gate and report.generated_diff and not report.safety_events:
                report.approval_status = 'pending'
                report.approval_notes = 'Shadow mode — awaiting human decision'
                # In production: present to human, wait for approve/reject/request_changes
                # In shadow mode: mark as pending, continue with report
            
            # ═══ STEP 8C: BLM learning record (RC43B Fix) ═══
            try:
                from coding_tentacle.memory.bug_learning_memory import BugLearningMemory
                import os as _os
                blm_dir = _os.path.expanduser('~/.coding_tentacle')
                _os.makedirs(blm_dir, exist_ok=True)
                blm_db = _os.path.join(blm_dir, 'learning.db')
                blm = BugLearningMemory(db_path=blm_db)
                blm.record_experience(
                    bug_signature=f"{bug_type}: {run.issue_title[:80]}",
                    bug_type=bug_type,
                    fix_type=report.engine_used or 'template',
                    root_cause=f"Engine: {report.engine_used}" if report.engine_used else 'Unknown',
                    fix_summary=report.generated_diff[:100] if report.generated_diff else 'No diff',
                    file_path=code_context.get('file', 'unknown'),
                    language='python',
                )
                report.blm_written = True
                report.blm_error = ''
            except Exception as e:
                report.blm_written = False
                report.blm_error = str(e)[:200]
            
            # ═══ STEP 8D: EngineLearning record (RC46 Fix1+3) ═══
            if report.engine_used:
                try:
                    from coding_tentacle.orchestrator.engine_learning import EnginePerformanceStore
                    eps = EnginePerformanceStore()
                    # Fix 1: Correct success detection
                    success = False
                    if report.test_result:
                        success = bool(report.test_result.get('tests_passed', 0) > 0 or report.test_result.get('success'))
                    elif report.generated_diff and not report.safety_events:
                        success = True  # Diff generated + safety clean = partial success
                    elif report.skeptic_recommendation == 'APPROVE':
                        success = True
                    
                    eps.record(
                        engine_name=report.engine_used,
                        bug_type=bug_type,
                        success=success,
                        runtime_s=report.duration_ms / 1000 if report.duration_ms else 0,
                        skeptic_risk=getattr(report, 'skeptic_risk', 0.0),
                        impact_risk=getattr(report, 'impact_risk', 0.0),
                    )
                except Exception:
                    pass  # Engine learning failure is non-fatal
            
            # ═══ STEP 8E: Self-Observation Audit (RC54) ═══
            report.observation = ''
            try:
                from coding_tentacle.brains.self_observation_brain import SelfObservationBrain, DecisionStep
                observer = SelfObservationBrain()
                trace = [
                    DecisionStep("ReflexLayer", "ALLOW" if not report.safety_events else "BLOCK", 0.95, "Reflex check"),
                    DecisionStep("Classifier", "GO", report.confidence, f"Type: {report.detected_bug_type}"),
                    DecisionStep("RootCauseBrain", "GO", report.root_cause_confidence, f"Cause: {report.root_cause}"),
                ]
                obs_report = observer.observe(
                    decision_trace=trace,
                    bug_type=report.detected_bug_type,
                    engine_used=report.engine_used,
                    engine_trust=0.60,
                    safety_warnings=report.safety_events if report.safety_events else None,
                    skeptic_risk=report.skeptic_risk,
                    test_passed=bool(report.test_result.get('success')) if report.test_result else None,
                    approval_status=report.approval_status,
                    root_cause=report.root_cause,
                )
                report.observation = obs_report.final_explanation
            except Exception:
                pass
            
            # ═══ STEP 8F: Evidence Ledger (RC59) ═══
            try:
                from coding_tentacle.audit.evidence_ledger import EvidenceLedger
                el = EvidenceLedger()
                el_report = el.record(
                    run_id=f'{repo_name}_{report.detected_bug_type}',
                    bug_report=bug_report,
                    bug_type=report.detected_bug_type,
                    root_cause=report.root_cause,
                    engine_used=report.engine_used,
                    diff=report.generated_diff,
                    safety_warnings=report.safety_events if report.safety_events else None,
                    skeptic_risk=report.skeptic_risk,
                    test_passed=bool(report.test_result.get('success')) if report.test_result else None,
                    approval_status=report.approval_status,
                )
                report.evidence_ledger_path = el_report.report_path
            except Exception:
                pass  # Observation is bonus, never blocks pipeline
            
            # ═══ STEP 9: Recommendation ═══
            if report.safety_events:
                report.recommendation = "DO NOT APPLY — Safety concern"
            elif report.test_result.get('success'):
                report.recommendation = "Ready for human review — tests pass in sandbox"
            elif report.detected_bug_type == 'Unknown':
                report.recommendation = "Cannot classify — needs human triage"
            else:
                report.recommendation = "Analyzed — needs human verification before apply"
            
        finally:
            # Cleanup workspace
            shutil.rmtree(workspace, ignore_errors=True)
        
        report.duration_ms = (time.time() - t0) * 1000
        self.runs.append(report)
        return report
    
    def _classify_bug_type(self, bug_report):
        """Classify bug type from issue text. 13+ types supported."""
        text = bug_report.lower()
        
        # Core types (6 — existing, high confidence)
        if any(w in text for w in ['null', 'none', 'nonetype', 'none reference',
                                     'has no attribute', 'optional', 'none value']):
            return 'NullPointer'
        if any(w in text for w in ['type', 'typeerror', 'cannot concatenate',
                                     'unsupported operand', 'multiply.*non-int', 'str and int',
                                     'bytes', 'str and bytes']):
            return 'TypeError'
        if any(w in text for w in ['import', 'modulenotfound', 'no module',
                                     'cannot import', 'circular import']):
            return 'ImportError'
        if any(w in text for w in ['attribute', 'attributeerror', 'has no attribute']):
            if not any(w in text for w in ['none', 'nonetype']):
                return 'AttributeError'
        if any(w in text for w in ['key', 'keyerror', 'missing key']):
            return 'KeyError'
        
        # Extended types (7 NEW — RC15.7)
        if any(w in text for w in ['indexerror', 'list index', 'out of range',
                                     'off-by-one', 'index out of bounds']):
            return 'IndexError'
        if any(w in text for w in ['valueerror', 'invalid literal', 'invalid value',
                                     'string where int', 'invalid for int']):
            return 'ValueError'
        if any(w in text for w in ['memoryerror', 'out of memory', 'oom',
                                     'memory leak', 'garbage collection']):
            return 'MemoryError'
        if any(w in text for w in ['syntaxerror', 'invalid syntax', 'syntax error',
                                     'version mismatch', 'python version']):
            return 'SyntaxError'
        if any(w in text for w in ['connection', 'connectionrefused', 'timeout',
                                     'refused', 'network', 'connection error']):
            return 'ConnectionError'
        if any(w in text for w in ['race condition', 'racecondition', 'deadlock',
                                     'concurrency', 'thread safety', 'startup race']):
            return 'RaceCondition'
        if any(w in text for w in ['performance', 'slow', 'n+1', 'loading',
                                     'load time', 'page load', 'optimiz']):
            return 'Performance'
        
        # Security (highest priority — check LAST to avoid false positives)
        if any(w in text for w in ['drop table', 'sql injection', 'xss',
                                     'eval(', 'shell injection', 'api_key']):
            return 'SecurityRisk'
        
        return 'Unknown'
    
    def run_batch(self, issues: list[GitHubIssueRun]) -> list[ShadowRunReport]:
        """Analyze multiple issues sequentially."""
        results = []
        for issue in issues:
            result = self.analyze_issue(issue)
            results.append(result)
        return results
    
    def stats(self):
        return {
            'total_runs': len(self.runs),
            'classified': sum(1 for r in self.runs if r.detected_bug_type != 'Unknown'),
            'safety_blocked': sum(1 for r in self.runs if r.safety_events),
            'actions_executed': 0,
        }


# ═══════════ TEST ═══════════
if __name__ == "__main__":
    from coding_tentacle.orchestrator.metabrain import MetaBrain, SafetyBrain
    from coding_tentacle.safety.inhibitory_control import InhibitoryControl
    from coding_tentacle.knowledge.security_store import create_seed_security_store
    from coding_tentacle.orchestrator.teacher_student import Teacher
    from coding_tentacle.patch.diff_generator import DiffGenerator
    from coding_tentacle.patch.patch_suggestion import PatchSuggestionEngine
    
    print("SHADOW MODE / GITHUB ISSUE DRY-RUN — Self-Test")
    print("=" * 55)
    passed = 0
    
    sec = create_seed_security_store()
    ic = InhibitoryControl(security_store=sec)
    safety = SafetyBrain(ic=ic, security_store=sec)
    mb = MetaBrain(safety=safety)
    t = Teacher()
    ps = PatchSuggestionEngine()
    dg = DiffGenerator(safety_brain=safety, patch_suggestion=ps)
    runner = ShadowModeRunner(meta_brain=mb, teacher=t, diff_generator=dg)
    
    # T1: Analyze safe issue
    issue1 = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/1",
        issue_title="NullPointerException when accessing user profile",
        issue_body="Getting NoneType error when user profile is not loaded.",
    )
    report = runner.analyze_issue(issue1)
    t1 = report.detected_bug_type != 'Unknown'
    print(f"  T1: {'✅' if t1 else '❌'} Safe issue → {report.detected_bug_type}")
    
    # T2: Report has recommendation
    t2 = report.recommendation
    print(f"  T2: {'✅' if t2 else '❌'} Recommendation → {report.recommendation[:60]}")
    
    # T3: Diff generated
    t3 = bool(report.generated_diff)
    print(f"  T3: {'✅' if t3 else '❌'} Diff generated → {len(report.generated_diff)} chars")
    
    # T4: Security issue blocked
    issue_sec = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/2",
        issue_title="SQL Injection in login form",
        issue_body="DROP TABLE users via eval() injection",
    )
    report_sec = runner.analyze_issue(issue_sec)
    t4 = report_sec.detected_bug_type == 'SecurityRisk' or len(report_sec.safety_events) > 0
    print(f"  T4: {'✅' if t4 else '❌'} Security issue → {report_sec.detected_bug_type}")
    
    # T5: Unknown issue handled
    issue_unk = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/3",
        issue_title="Something is broken",
        issue_body="I don't know what happened but the app crashed.",
    )
    report_unk = runner.analyze_issue(issue_unk)
    t5 = report_unk.detected_bug_type == 'Unknown'
    print(f"  T5: {'✅' if t5 else '❌'} Unknown issue → {report_unk.detected_bug_type}")
    
    # T6: Markdown report
    md = report.to_markdown()
    t6 = 'Shadow Run Report' in md and 'Bug Type' in md
    print(f"  T6: {'✅' if t6 else '❌'} Markdown report → {len(md)} chars")
    
    # T7: Stats read-only
    st = runner.stats()
    t7 = st['actions_executed'] == 0
    print(f"  T7: {'✅' if t7 else '❌'} Stats → read-only")
    
    passed = sum([t1,t2,t3,t4,t5,t6,t7])
    print(f"\n  {'='*55}")
    print(f"  ERGEBNIS: {passed}/7 Tests bestanden")
    print(f"  {'✅ SHADOW MODE FERTIG' if passed >= 6 else '⚠️'}")
