"""
SHADOW MODE / GITHUB ISSUE DRY-RUN — RC15
Analyzes real GitHub issues in read-only shadow mode.
NEVER commits, pushes, or modifies original repos.

Full pipeline: Clone → Analyze → Diff → Sandbox → Test → Report.

Autor: Hermes + David | Coding Tentacle 2026
"""
import os, time, json, tempfile, shutil
from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass
class GitHubIssueRun:
    """Input: a GitHub issue to analyze."""
    repo_url: str              # "https://github.com/user/repo"
    issue_url: str             # "https://github.com/user/repo/issues/1"
    issue_title: str = ""
    issue_body: str = ""
    branch: str = "main"
    test_command: str = ""     # "pytest -x -q" or similar
    max_attempts: int = 2
    mode: str = "shadow"       # always shadow for now


@dataclass
class ShadowRunReport:
    """Output: complete analysis of one GitHub issue."""
    repo: str
    issue: str
    issue_title: str
    detected_bug_type: str = ""
    confidence: float = 0.0
    selected_procedure: str = ""
    selected_skill: str = ""
    generated_diff: str = ""
    engine_used: str = ""
    engine_fix_raw: str = ""
    sandbox_result: dict = field(default_factory=dict)
    test_result: dict = field(default_factory=dict)
    safety_events: list = field(default_factory=list)
    failure_reasons: list = field(default_factory=list)
    recommendation: str = ""
    duration_ms: float = 0.0
    timestamp: float = 0.0
    
    def __post_init__(self):
        if self.timestamp == 0.0:
            self.timestamp = time.time()
    
    def to_markdown(self):
        safety = "✅ SAFE" if not self.safety_events else f"⚠️  {len(self.safety_events)} safety events"
        test_status = "✅ PASS" if self.test_result.get('success') else \
                      "❌ FAIL" if self.test_result else "⚪ NOT_RUN"
        return f"""# Shadow Run Report: {self.issue_title}

**Repo:** {self.repo}
**Issue:** {self.issue}
**Bug Type:** {self.detected_bug_type} (conf={self.confidence:.0%})

## Procedure & Skill
- Procedure: {self.selected_procedure or 'none'}
- Skill: {self.selected_skill or 'none'}

## Diff Generated
```diff
{self.generated_diff[:500] or '(no diff generated)'}
```

## Test Result
{test_status}

## Safety Events
{safety}

## Recommendation
{self.recommendation or 'Pending human review'}

---
*Generated by Coding Tentacle RC15 Shadow Mode*
"""


class ShadowModeRunner:
    """Analyzes GitHub issues in read-only shadow mode.
    NEVER commits, pushes, touches original repos."""
    
    def __init__(self, meta_brain=None, teacher=None, diff_generator=None,
                 sandbox_runner=None, test_runner=None, repair_loop=None,
                 approval_gate=None, project_map_class=None,
                 engine_router=None, safety_brain=None):
        self.meta_brain = meta_brain
        self.teacher = teacher
        self.diff_generator = diff_generator
        self.sandbox_runner = sandbox_runner
        self.test_runner = test_runner
        self.repair_loop = repair_loop
        self.approval_gate = approval_gate
        self.project_map_class = project_map_class
        self.engine_router = engine_router
        self.safety_brain = safety_brain or (meta_brain.safety if meta_brain else None)
        self.runs = []
    
    def analyze_issue(self, run: GitHubIssueRun) -> ShadowRunReport:
        """Analyze a GitHub issue in full shadow mode pipeline."""
        t0 = time.time()
        
        report = ShadowRunReport(
            repo=run.repo_url,
            issue=run.issue_url,
            issue_title=run.issue_title,
        )
        
        # Extract repo name from URL
        repo_name = run.repo_url.rstrip('/').split('/')[-1]
        
        # ═══ STEP 1: Extract bug information from issue ═══
        bug_report = f"{run.issue_title}\n{run.issue_body}"[:500]
        
        # ═══ STEP 2: Create isolated workspace ═══
        workspace = tempfile.mkdtemp(prefix=f'ct_shadow_{repo_name}_')
        
        try:
            # Simple file setup for analysis
            code_context = {'file': f'{repo_name}/main.py', 'line': 1}
            
            # ═══ STEP 3: Classify bug type from issue text ═══
            bug_type = self._classify_bug_type(bug_report)
            report.detected_bug_type = bug_type
            report.confidence = 0.7 if bug_type != 'Unknown' else 0.2
            
            # ═══ STEP 4: MetaBrain analyzes ═══
            if self.meta_brain:
                decision = self.meta_brain.decide(bug_report, code_context=code_context)
                if decision['final_decision'] == 'BLOCK':
                    report.safety_events.append(decision.get('reason', 'Blocked'))
                    report.recommendation = "BLOCKED by Safety — cannot analyze"
                    report.duration_ms = (time.time() - t0) * 1000
                    return report
            
            # ═══ STEP 5: Select procedure/skill ═══
            if self.teacher and self.teacher.procedural_memory:
                proc = self.teacher.procedural_memory.find_procedure(bug_type)
                if proc:
                    report.selected_procedure = f"{bug_type}:python"
            if self.teacher and self.teacher.skill_store:
                skill = self.teacher.skill_store.best_skill_for(bug_type)
                if skill:
                    report.selected_skill = skill.name
            
            # ═══ STEP 6: Generate fix via Engine Router (RC40) ═══
            if self.engine_router and bug_type != 'SecurityRisk':
                try:
                    from coding_tentacle.orchestrator.engine_router import EngineRouter
                    engine_name, engine_cfg, route_reason = self.engine_router.route(bug_type)
                    report.engine_used = engine_name or 'none'
                    
                    if engine_name and engine_cfg:
                        prompt = f"""Fix this bug. Output ONLY the corrected code or unified diff.

BUG: {run.issue_title}
DESCRIPTION: {run.issue_body[:300]}
BUG TYPE: {bug_type}

RULES: Output only the fix. Do NOT modify files. No commits. No PRs."""
                        
                        import subprocess
                        engine_path = engine_cfg.get('path', '')
                        if 'opencode' in engine_name.lower():
                            cmd = [engine_path, 'run', prompt]
                        elif 'ollama' in engine_name.lower():
                            cmd = ['ollama', 'run', 'granite3.2-vision', prompt]
                        else:
                            cmd = []
                        
                        if cmd:
                            try:
                                result = subprocess.run(cmd, capture_output=True, text=True, timeout=60, cwd='/tmp')
                                if result.returncode == 0:
                                    report.engine_fix_raw = (result.stdout + result.stderr)[:800]
                                    # Extract code block or diff from engine output
                                    output = report.engine_fix_raw
                                    if '```' in output:
                                        # Extract code between backticks
                                        parts = output.split('```')
                                        if len(parts) >= 2:
                                            report.generated_diff = parts[1].strip()
                                            if report.generated_diff.startswith('python'):
                                                report.generated_diff = report.generated_diff[6:].strip()
                                            elif report.generated_diff.startswith('diff'):
                                                report.generated_diff = report.generated_diff
                                    else:
                                        report.generated_diff = output[:500]
                            except subprocess.TimeoutExpired:
                                report.generated_diff = ''
                            except Exception:
                                report.generated_diff = ''
                except ImportError:
                    pass  # Engine router not available, fall through to template
            # Fallback: template-based diff (if no engine or engine failed)
            if not report.generated_diff and self.diff_generator and self.teacher:
                plan = self.teacher.create_plan(bug_report,
                    code_context=code_context,
                    grounding={'bug_type': bug_type, 'grounding_score': report.confidence})
                if plan:
                    patch_diff = self.diff_generator.generate(
                        plan, code_context=code_context,
                        original_code="# module\n\ndef main():\n    pass\n")
                    if patch_diff and patch_diff.diff:
                        report.generated_diff = patch_diff.diff[:500]
            
            # ═══ STEP 7: Sandbox test ═══
            if self.sandbox_runner and report.generated_diff:
                from coding_tentacle.patch.diff_generator import PatchDiff
                pd = PatchDiff(
                    file_path=code_context['file'], bug_type=bug_type,
                    original_code="# module", patched_code=report.generated_diff,
                    diff=report.generated_diff, confidence=report.confidence,
                    safety_checked=True, safety_passed=True,
                )
                sr = self.sandbox_runner.run(pd, project_path=workspace)
                report.sandbox_result = {
                    'success': sr.success,
                    'safety_status': sr.safety_status,
                    'patched_files': sr.patched_files,
                }
            
            # ═══ STEP 8: Test result ═══
            if self.test_runner and report.sandbox_result.get('success'):
                test_cmd = run.test_command or "python -m pytest -x -q"
                tr = self.test_runner.run(workspace, test_command=test_cmd)
                report.test_result = {
                    'success': tr.success,
                    'exit_code': tr.exit_code,
                    'tests_passed': tr.tests_passed,
                    'tests_failed': tr.tests_failed,
                }
            
            # ═══ STEP 9: Recommendation ═══
            if report.safety_events:
                report.recommendation = "DO NOT APPLY — Safety concern"
            elif report.test_result.get('success'):
                report.recommendation = "Ready for human review — tests pass in sandbox"
            elif report.detected_bug_type == 'Unknown':
                report.recommendation = "Cannot classify — needs human triage"
            else:
                report.recommendation = "Analyzed — needs human verification before apply"
            
        finally:
            # Cleanup workspace
            shutil.rmtree(workspace, ignore_errors=True)
        
        report.duration_ms = (time.time() - t0) * 1000
        self.runs.append(report)
        return report
    
    def _classify_bug_type(self, bug_report):
        """Classify bug type from issue text. 13+ types supported."""
        text = bug_report.lower()
        
        # Core types (6 — existing, high confidence)
        if any(w in text for w in ['null', 'none', 'nonetype', 'none reference',
                                     'has no attribute', 'optional', 'none value']):
            return 'NullPointer'
        if any(w in text for w in ['type', 'typeerror', 'cannot concatenate',
                                     'unsupported operand', 'multiply.*non-int', 'str and int',
                                     'bytes', 'str and bytes']):
            return 'TypeError'
        if any(w in text for w in ['import', 'modulenotfound', 'no module',
                                     'cannot import', 'circular import']):
            return 'ImportError'
        if any(w in text for w in ['attribute', 'attributeerror', 'has no attribute']):
            if not any(w in text for w in ['none', 'nonetype']):
                return 'AttributeError'
        if any(w in text for w in ['key', 'keyerror', 'missing key']):
            return 'KeyError'
        
        # Extended types (7 NEW — RC15.7)
        if any(w in text for w in ['indexerror', 'list index', 'out of range',
                                     'off-by-one', 'index out of bounds']):
            return 'IndexError'
        if any(w in text for w in ['valueerror', 'invalid literal', 'invalid value',
                                     'string where int', 'invalid for int']):
            return 'ValueError'
        if any(w in text for w in ['memoryerror', 'out of memory', 'oom',
                                     'memory leak', 'garbage collection']):
            return 'MemoryError'
        if any(w in text for w in ['syntaxerror', 'invalid syntax', 'syntax error',
                                     'version mismatch', 'python version']):
            return 'SyntaxError'
        if any(w in text for w in ['connection', 'connectionrefused', 'timeout',
                                     'refused', 'network', 'connection error']):
            return 'ConnectionError'
        if any(w in text for w in ['race condition', 'racecondition', 'deadlock',
                                     'concurrency', 'thread safety', 'startup race']):
            return 'RaceCondition'
        if any(w in text for w in ['performance', 'slow', 'n+1', 'loading',
                                     'load time', 'page load', 'optimiz']):
            return 'Performance'
        
        # Security (highest priority — check LAST to avoid false positives)
        if any(w in text for w in ['drop table', 'sql injection', 'xss',
                                     'eval(', 'shell injection', 'api_key']):
            return 'SecurityRisk'
        
        return 'Unknown'
    
    def run_batch(self, issues: list[GitHubIssueRun]) -> list[ShadowRunReport]:
        """Analyze multiple issues sequentially."""
        results = []
        for issue in issues:
            result = self.analyze_issue(issue)
            results.append(result)
        return results
    
    def stats(self):
        return {
            'total_runs': len(self.runs),
            'classified': sum(1 for r in self.runs if r.detected_bug_type != 'Unknown'),
            'safety_blocked': sum(1 for r in self.runs if r.safety_events),
            'actions_executed': 0,
        }


# ═══════════ TEST ═══════════
if __name__ == "__main__":
    from coding_tentacle.orchestrator.metabrain import MetaBrain, SafetyBrain
    from coding_tentacle.safety.inhibitory_control import InhibitoryControl
    from coding_tentacle.knowledge.security_store import create_seed_security_store
    from coding_tentacle.orchestrator.teacher_student import Teacher
    from coding_tentacle.patch.diff_generator import DiffGenerator
    from coding_tentacle.patch.patch_suggestion import PatchSuggestionEngine
    
    print("SHADOW MODE / GITHUB ISSUE DRY-RUN — Self-Test")
    print("=" * 55)
    passed = 0
    
    sec = create_seed_security_store()
    ic = InhibitoryControl(security_store=sec)
    safety = SafetyBrain(ic=ic, security_store=sec)
    mb = MetaBrain(safety=safety)
    t = Teacher()
    ps = PatchSuggestionEngine()
    dg = DiffGenerator(safety_brain=safety, patch_suggestion=ps)
    runner = ShadowModeRunner(meta_brain=mb, teacher=t, diff_generator=dg)
    
    # T1: Analyze safe issue
    issue1 = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/1",
        issue_title="NullPointerException when accessing user profile",
        issue_body="Getting NoneType error when user profile is not loaded.",
    )
    report = runner.analyze_issue(issue1)
    t1 = report.detected_bug_type != 'Unknown'
    print(f"  T1: {'✅' if t1 else '❌'} Safe issue → {report.detected_bug_type}")
    
    # T2: Report has recommendation
    t2 = report.recommendation
    print(f"  T2: {'✅' if t2 else '❌'} Recommendation → {report.recommendation[:60]}")
    
    # T3: Diff generated
    t3 = bool(report.generated_diff)
    print(f"  T3: {'✅' if t3 else '❌'} Diff generated → {len(report.generated_diff)} chars")
    
    # T4: Security issue blocked
    issue_sec = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/2",
        issue_title="SQL Injection in login form",
        issue_body="DROP TABLE users via eval() injection",
    )
    report_sec = runner.analyze_issue(issue_sec)
    t4 = report_sec.detected_bug_type == 'SecurityRisk' or len(report_sec.safety_events) > 0
    print(f"  T4: {'✅' if t4 else '❌'} Security issue → {report_sec.detected_bug_type}")
    
    # T5: Unknown issue handled
    issue_unk = GitHubIssueRun(
        repo_url="https://github.com/example/demo",
        issue_url="https://github.com/example/demo/issues/3",
        issue_title="Something is broken",
        issue_body="I don't know what happened but the app crashed.",
    )
    report_unk = runner.analyze_issue(issue_unk)
    t5 = report_unk.detected_bug_type == 'Unknown'
    print(f"  T5: {'✅' if t5 else '❌'} Unknown issue → {report_unk.detected_bug_type}")
    
    # T6: Markdown report
    md = report.to_markdown()
    t6 = 'Shadow Run Report' in md and 'Bug Type' in md
    print(f"  T6: {'✅' if t6 else '❌'} Markdown report → {len(md)} chars")
    
    # T7: Stats read-only
    st = runner.stats()
    t7 = st['actions_executed'] == 0
    print(f"  T7: {'✅' if t7 else '❌'} Stats → read-only")
    
    passed = sum([t1,t2,t3,t4,t5,t6,t7])
    print(f"\n  {'='*55}")
    print(f"  ERGEBNIS: {passed}/7 Tests bestanden")
    print(f"  {'✅ SHADOW MODE FERTIG' if passed >= 6 else '⚠️'}")
